#! /bin/sh


# echo "export SLOTS=/sys/devices/bone_capemgr.9/slots" >> /root/.profile
# echo "export PINS=/sys/kernel/debug/pinctrl/44e10800.pinmux/pins" >> /root/.profile
# dtc -O dtb -o EBB-ENJ-Cape-00A0.dtbo -b 0 -@ EBB-ENJ-Cape.dts
# cp EBB-ENJ-Cape-00A0.dtbo /lib/firmware/
# echo "optargs=capemgr.enable_partno=BB-ADC,BB-I2C1,BB-UART4,am33xx_pwm,EBB-ENJ-Cape" >> /boot/uEnv.txt
# remove comment in "cape_disable=capemgr.disable_partno=BB-BONELT-HDMI,BB-BONELT-HDMIN"

